name: TWRP CI

on:
  workflow_dispatch:

jobs:
    compile:
        name: Compile site assets
        runs-on: ubuntu-18.04
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: tedwang/aosp-v5
                options: -v ${{ github.workspace }}:/var/www
                run: |
                    sudo apt update
